### ISSUE TITLE
Extra templated input files

### ISSUE THREAD

**Issue by nstauff** [watts-dev/watts#13]
Some codes (such as SAS4A) may use templated files in both the main input file and the associated files. We need to provide the option for the user to expend templated supplementary files. Maybe this could be done with `extra_inputs_tmpl` that would contain the list of extra inputs that would need to be extended.

**Comment by paulromano** [comment]
What about just having the first argument (`template_file`) accept one or more template files? i.e.
```Python
plugin = watts.PluginX('template1')
```
if you only have a single template, or
```Python
plugin = watts.PluginX(['template1', 'template2'])
```
if you have multiple

**Comment by nstauff** [comment]
@paulromano , I am not sure about that because we would not know which is the expended input file to execute - we need to be able to specify the following:
- main input file to execute (can be a template or not, but must be a text file)
- extra files - those are not templates and will just be passed along
- extra input templates - those are additional input files that we will want to expend prior to passing along

We could have several options:
`watts.PluginX(main_input = 'main.tmpl', supp_inputs=['main_in.e', 'sub.i'], supp_tmpl = ['supp1.tmpl'])` % heavier but more explicit
or:
`watts.PluginX('main.tmpl', supp_inputs=['main_in.e', 'sub.i', 'supp1.tmpl'])` % in this case, we force templated files to use '.tmpl' extension

**Comment by paulromano** [comment]
Another thought would be to adopt a convention of the first template listed being the primary one, i.e.
```Python
watts.PluginX(['main.tmpl', 'supp1.tmpl'], extra_inputs=['main_in.e', 'sub.i'])
```

**Comment by nstauff** [comment]
I had the same thought by I personally prefer it to be more explicit. Otherwise it will be error prone.

**Comment by paulromano** [comment]
You're right — [explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python) :+1:
